/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdTreeResponse {
    #[serde(rename = "campaigns", skip_serializing_if = "Option::is_none")]
    pub campaigns: Option<Vec<models::AdTreeCampaign>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::Pagination>>,
    /// Present and true while historical data is being backfilled.
    #[serde(rename = "backfillPending", skip_serializing_if = "Option::is_none")]
    pub backfill_pending: Option<bool>,
}

impl AdTreeResponse {
    pub fn new() -> AdTreeResponse {
        AdTreeResponse {
            campaigns: None,
            pagination: None,
            backfill_pending: None,
        }
    }
}
