/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddConversionAssociationsRequest {
    #[serde(rename = "adAccountId")]
    pub ad_account_id: String,
    #[serde(rename = "campaignIds")]
    pub campaign_ids: Vec<String>,
}

impl AddConversionAssociationsRequest {
    pub fn new(
        ad_account_id: String,
        campaign_ids: Vec<String>,
    ) -> AddConversionAssociationsRequest {
        AddConversionAssociationsRequest {
            ad_account_id,
            campaign_ids,
        }
    }
}
