/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchGetGoogleBusinessReviewsRequest {
    /// Array of full location resource names (e.g. ['accounts/123/locations/456'])
    #[serde(rename = "locationNames")]
    pub location_names: Vec<String>,
    /// Number of reviews per page (max 50)
    #[serde(rename = "pageSize", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
    /// Pagination token from previous response
    #[serde(rename = "pageToken", skip_serializing_if = "Option::is_none")]
    pub page_token: Option<String>,
}

impl BatchGetGoogleBusinessReviewsRequest {
    pub fn new(location_names: Vec<String>) -> BatchGetGoogleBusinessReviewsRequest {
        BatchGetGoogleBusinessReviewsRequest {
            location_names,
            page_size: None,
            page_token: None,
        }
    }
}
