/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkUpdateAdCampaignStatus200ResponseTotals {
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<i32>,
    #[serde(rename = "skipped", skip_serializing_if = "Option::is_none")]
    pub skipped: Option<i32>,
    #[serde(rename = "failed", skip_serializing_if = "Option::is_none")]
    pub failed: Option<i32>,
}

impl BulkUpdateAdCampaignStatus200ResponseTotals {
    pub fn new() -> BulkUpdateAdCampaignStatus200ResponseTotals {
        BulkUpdateAdCampaignStatus200ResponseTotals {
            updated: None,
            skipped: None,
            failed: None,
        }
    }
}
