/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BusinessAgentSettingsHandoff {
    /// Whether the agent releases the thread after sending its handoff message.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "message_selection", skip_serializing_if = "Option::is_none")]
    pub message_selection: Option<MessageSelection>,
}

impl BusinessAgentSettingsHandoff {
    pub fn new() -> BusinessAgentSettingsHandoff {
        BusinessAgentSettingsHandoff {
            enabled: None,
            message: None,
            message_selection: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MessageSelection {
    #[serde(rename = "DEFAULT")]
    Default,
    #[serde(rename = "AGENT")]
    Agent,
    #[serde(rename = "CUSTOM")]
    Custom,
}

impl Default for MessageSelection {
    fn default() -> MessageSelection {
        Self::Default
    }
}
