/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CampaignBiddingPortfolio : Set only when the campaign is on a portfolio bid strategy (campaign.bidding_strategy); null otherwise.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CampaignBiddingPortfolio {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl CampaignBiddingPortfolio {
    /// Set only when the campaign is on a portfolio bid strategy (campaign.bidding_strategy); null otherwise.
    pub fn new() -> CampaignBiddingPortfolio {
        CampaignBiddingPortfolio {
            id: None,
            name: None,
        }
    }
}
