/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommentAutomationTemplateElementButtonsInner {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "title")]
    pub title: String,
    /// Target URL (required when type is url)
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Postback payload delivered via the messaging_postbacks webhook (required when type is postback)
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<String>,
}

impl CommentAutomationTemplateElementButtonsInner {
    pub fn new(r#type: Type, title: String) -> CommentAutomationTemplateElementButtonsInner {
        CommentAutomationTemplateElementButtonsInner {
            r#type,
            title,
            url: None,
            payload: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "url")]
    Url,
    #[serde(rename = "postback")]
    Postback,
}

impl Default for Type {
    fn default() -> Type {
        Self::Url
    }
}
