/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigureTikTokAdsBrandIdentityRequest {
    /// SocialAccount ID of the `tiktokads` account.
    #[serde(rename = "accountId")]
    pub account_id: String,
    /// Brand name shown above the ad on TikTok.
    #[serde(rename = "displayName")]
    pub display_name: String,
    /// Public URL of a square brand image (≥98×98 px, JPG/PNG, max 5 MB). Used as the brand avatar on the ad.
    #[serde(rename = "imageUrl")]
    pub image_url: String,
}

impl ConfigureTikTokAdsBrandIdentityRequest {
    pub fn new(
        account_id: String,
        display_name: String,
        image_url: String,
    ) -> ConfigureTikTokAdsBrandIdentityRequest {
        ConfigureTikTokAdsBrandIdentityRequest {
            account_id,
            display_name,
            image_url,
        }
    }
}
