/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.15.0
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectWordPressWithApplicationPasswordRequest {
    /// Your Zernio profile ID (get from /v1/profiles).
    #[serde(rename = "profileId")]
    pub profile_id: String,
    /// HTTPS base URL of the WordPress installation, including a subdirectory path when applicable.
    #[serde(rename = "siteUrl")]
    pub site_url: String,
    /// WordPress login name. A colon is not allowed.
    #[serde(rename = "username")]
    pub username: String,
    /// Application password created for the WordPress user. Spaces in WordPress display formatting are accepted.
    #[serde(rename = "applicationPassword")]
    pub application_password: String,
}

impl ConnectWordPressWithApplicationPasswordRequest {
    pub fn new(
        profile_id: String,
        site_url: String,
        username: String,
        application_password: String,
    ) -> ConnectWordPressWithApplicationPasswordRequest {
        ConnectWordPressWithApplicationPasswordRequest {
            profile_id,
            site_url,
            username,
            application_password,
        }
    }
}
