/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectWhatsAppCredentials200ResponseAccount {
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<Platform>,
    /// Display phone number
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// Meta-verified business name
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "isActive", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    /// The connected phone number
    #[serde(
        rename = "selectedPhoneNumber",
        skip_serializing_if = "Option::is_none"
    )]
    pub selected_phone_number: Option<String>,
}

impl ConnectWhatsAppCredentials200ResponseAccount {
    pub fn new() -> ConnectWhatsAppCredentials200ResponseAccount {
        ConnectWhatsAppCredentials200ResponseAccount {
            account_id: None,
            platform: None,
            username: None,
            display_name: None,
            is_active: None,
            selected_phone_number: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Platform {
    #[serde(rename = "whatsapp")]
    Whatsapp,
}

impl Default for Platform {
    fn default() -> Platform {
        Self::Whatsapp
    }
}
