/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateInboxConversationRequestTemplateCardsInnerButtonsInner {
    /// Zero-based position of the button within the card's buttons.
    #[serde(rename = "index")]
    pub index: i32,
    /// The button kind, which decides how the value is sent.
    #[serde(rename = "subType")]
    pub sub_type: SubType,
    /// The value to send (quick_reply payload, or the URL dynamic suffix).
    #[serde(rename = "value")]
    pub value: String,
}

impl CreateInboxConversationRequestTemplateCardsInnerButtonsInner {
    pub fn new(
        index: i32,
        sub_type: SubType,
        value: String,
    ) -> CreateInboxConversationRequestTemplateCardsInnerButtonsInner {
        CreateInboxConversationRequestTemplateCardsInnerButtonsInner {
            index,
            sub_type,
            value,
        }
    }
}
/// The button kind, which decides how the value is sent.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SubType {
    #[serde(rename = "quick_reply")]
    QuickReply,
    #[serde(rename = "url")]
    Url,
}

impl Default for SubType {
    fn default() -> SubType {
        Self::QuickReply
    }
}
