/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCustomFieldRequest {
    #[serde(rename = "profileId")]
    pub profile_id: String,
    #[serde(rename = "name")]
    pub name: String,
    /// Auto-generated from name if not provided
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Required for select type
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<String>>,
}

impl CreateCustomFieldRequest {
    pub fn new(profile_id: String, name: String, r#type: Type) -> CreateCustomFieldRequest {
        CreateCustomFieldRequest {
            profile_id,
            name,
            slug: None,
            r#type,
            options: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "number")]
    Number,
    #[serde(rename = "date")]
    Date,
    #[serde(rename = "boolean")]
    Boolean,
    #[serde(rename = "select")]
    Select,
}

impl Default for Type {
    fn default() -> Type {
        Self::Text
    }
}
