/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateBlogArticleRequestImage : Featured image. The platform downloads it, so the URL must be publicly reachable.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBlogArticleRequestImage {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "altText", skip_serializing_if = "Option::is_none")]
    pub alt_text: Option<String>,
}

impl CreateBlogArticleRequestImage {
    /// Featured image. The platform downloads it, so the URL must be publicly reachable.
    pub fn new(url: String) -> CreateBlogArticleRequestImage {
        CreateBlogArticleRequestImage {
            url,
            alt_text: None,
        }
    }
}
