/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.
 *
 * The version of the OpenAPI document: 1.250.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSupportRun202Response {
    #[serde(rename = "runId")]
    pub run_id: String,
    #[serde(rename = "threadId")]
    pub thread_id: String,
    #[serde(rename = "status")]
    pub status: Status,
    /// Seconds to wait before the first poll.
    #[serde(rename = "pollAfterSeconds")]
    pub poll_after_seconds: i32,
}

impl CreateSupportRun202Response {
    pub fn new(
        run_id: String,
        thread_id: String,
        status: Status,
        poll_after_seconds: i32,
    ) -> CreateSupportRun202Response {
        CreateSupportRun202Response {
            run_id,
            thread_id,
            status,
            poll_after_seconds,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "queued")]
    Queued,
}

impl Default for Status {
    fn default() -> Status {
        Self::Queued
    }
}
