/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CtwaSingleResponse : Response returned by `POST /v1/ads/ctwa` when the request used the single-creative shape (top-level headline / body / imageUrl|video). `adType` is the union discriminator.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CtwaSingleResponse {
    #[serde(rename = "adType")]
    pub ad_type: AdType,
    /// The persisted Ad document.
    #[serde(rename = "ad")]
    pub ad: serde_json::Value,
    #[serde(rename = "message")]
    pub message: String,
}

impl CtwaSingleResponse {
    /// Response returned by `POST /v1/ads/ctwa` when the request used the single-creative shape (top-level headline / body / imageUrl|video). `adType` is the union discriminator.
    pub fn new(ad_type: AdType, ad: serde_json::Value, message: String) -> CtwaSingleResponse {
        CtwaSingleResponse {
            ad_type,
            ad,
            message,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AdType {
    #[serde(rename = "single")]
    Single,
}

impl Default for AdType {
    fn default() -> AdType {
        Self::Single
    }
}
