/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscordGuildMemberUser {
    /// User snowflake
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "discriminator", skip_serializing_if = "Option::is_none")]
    pub discriminator: Option<String>,
    #[serde(
        rename = "avatar",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub avatar: Option<Option<String>>,
    /// User's display name (post-2023 Discord rebrand)
    #[serde(
        rename = "global_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub global_name: Option<Option<String>>,
}

impl DiscordGuildMemberUser {
    pub fn new() -> DiscordGuildMemberUser {
        DiscordGuildMemberUser {
            id: None,
            username: None,
            discriminator: None,
            avatar: None,
            global_name: None,
        }
    }
}
