/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DmButton : A single inline button rendered inside an auto-DM via Meta's button_template. Up to 3 buttons per automation. `url` and `postback` work on Instagram and Facebook; `phone` is Facebook-only. When buttons are set, `dmMessage` becomes the button_template text and must be 640 characters or less.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DmButton {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Button label (20 chars max)
    #[serde(rename = "title")]
    pub title: String,
    /// Target URL (required when type is url)
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Postback payload delivered via the messaging_postbacks webhook (required when type is postback)
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<String>,
    /// Phone number, e.g. +14155551234 (required when type is phone; Facebook only)
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
}

impl DmButton {
    /// A single inline button rendered inside an auto-DM via Meta's button_template. Up to 3 buttons per automation. `url` and `postback` work on Instagram and Facebook; `phone` is Facebook-only. When buttons are set, `dmMessage` becomes the button_template text and must be 640 characters or less.
    pub fn new(r#type: Type, title: String) -> DmButton {
        DmButton {
            r#type,
            title,
            url: None,
            payload: None,
            phone: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "url")]
    Url,
    #[serde(rename = "postback")]
    Postback,
    #[serde(rename = "phone")]
    Phone,
}

impl Default for Type {
    fn default() -> Type {
        Self::Url
    }
}
