/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadYouTubeVideo200Response {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "downloadUrl", skip_serializing_if = "Option::is_none")]
    pub download_url: Option<String>,
    #[serde(rename = "formats", skip_serializing_if = "Option::is_none")]
    pub formats: Option<Vec<models::DownloadYouTubeVideo200ResponseFormatsInner>>,
}

impl DownloadYouTubeVideo200Response {
    pub fn new() -> DownloadYouTubeVideo200Response {
        DownloadYouTubeVideo200Response {
            success: None,
            title: None,
            download_url: None,
            formats: None,
        }
    }
}
