/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FollowerStatsResponseStatsValueInner {
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "followers", skip_serializing_if = "Option::is_none")]
    pub followers: Option<f64>,
}

impl FollowerStatsResponseStatsValueInner {
    pub fn new() -> FollowerStatsResponseStatsValueInner {
        FollowerStatsResponseStatsValueInner {
            date: None,
            followers: None,
        }
    }
}
