/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FollowUserRequest {
    /// The social account ID
    #[serde(rename = "accountId")]
    pub account_id: String,
    /// The Twitter ID of the user to follow
    #[serde(rename = "targetUserId")]
    pub target_user_id: String,
}

impl FollowUserRequest {
    pub fn new(account_id: String, target_user_id: String) -> FollowUserRequest {
        FollowUserRequest {
            account_id,
            target_user_id,
        }
    }
}
