/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetInboxVolume200ResponseSummary {
    #[serde(rename = "received", skip_serializing_if = "Option::is_none")]
    pub received: Option<i32>,
    #[serde(rename = "sent", skip_serializing_if = "Option::is_none")]
    pub sent: Option<i32>,
    #[serde(rename = "read", skip_serializing_if = "Option::is_none")]
    pub read: Option<i32>,
    #[serde(rename = "failed", skip_serializing_if = "Option::is_none")]
    pub failed: Option<i32>,
    #[serde(
        rename = "uniqueConversations",
        skip_serializing_if = "Option::is_none"
    )]
    pub unique_conversations: Option<i32>,
}

impl GetInboxVolume200ResponseSummary {
    pub fn new() -> GetInboxVolume200ResponseSummary {
        GetInboxVolume200ResponseSummary {
            received: None,
            sent: None,
            read: None,
            failed: None,
            unique_conversations: None,
        }
    }
}
