/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetIosFourteenCampaignLimits200ResponseLimits {
    /// Campaign group limit reported by Meta.
    #[serde(
        rename = "campaignGroupLimit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub campaign_group_limit: Option<Option<f64>>,
    /// Campaign limit reported by Meta.
    #[serde(
        rename = "campaignLimit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub campaign_limit: Option<Option<f64>>,
    /// Campaign group limit details returned by Meta.
    #[serde(
        rename = "campaignGroupLimitsDetails",
        skip_serializing_if = "Option::is_none"
    )]
    pub campaign_group_limits_details: Option<Vec<serde_json::Value>>,
}

impl GetIosFourteenCampaignLimits200ResponseLimits {
    pub fn new() -> GetIosFourteenCampaignLimits200ResponseLimits {
        GetIosFourteenCampaignLimits200ResponseLimits {
            campaign_group_limit: None,
            campaign_limit: None,
            campaign_group_limits_details: None,
        }
    }
}
