/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWhatsAppDisplayName200ResponseDisplayName {
    /// Current verified display name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Meta review status for the display name
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Display phone number
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
}

impl GetWhatsAppDisplayName200ResponseDisplayName {
    pub fn new() -> GetWhatsAppDisplayName200ResponseDisplayName {
        GetWhatsAppDisplayName200ResponseDisplayName {
            name: None,
            status: None,
            phone_number: None,
        }
    }
}
/// Meta review status for the display name
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "APPROVED")]
    Approved,
    #[serde(rename = "PENDING_REVIEW")]
    PendingReview,
    #[serde(rename = "DECLINED")]
    Declined,
    #[serde(rename = "NONE")]
    None,
}

impl Default for Status {
    fn default() -> Status {
        Self::Approved
    }
}
