/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPhoneNumberKycForm200ResponseFieldsInner {
    #[serde(rename = "requirementId", skip_serializing_if = "Option::is_none")]
    pub requirement_id: Option<String>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// \"action\" = an out-of-band verification (e.g. Onfido); not filled here, fulfilled after the order via a link.
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<Kind>,
    /// Plain-English explanation of what to provide.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// Concrete example value.
    #[serde(
        rename = "example",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub example: Option<Option<String>>,
    /// ISO country the value must be local to
    #[serde(
        rename = "localTo",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub local_to: Option<Option<String>>,
}

impl GetPhoneNumberKycForm200ResponseFieldsInner {
    pub fn new() -> GetPhoneNumberKycForm200ResponseFieldsInner {
        GetPhoneNumberKycForm200ResponseFieldsInner {
            requirement_id: None,
            label: None,
            kind: None,
            description: None,
            example: None,
            local_to: None,
        }
    }
}
/// \"action\" = an out-of-band verification (e.g. Onfido); not filled here, fulfilled after the order via a link.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "date")]
    Date,
    #[serde(rename = "address")]
    Address,
    #[serde(rename = "file")]
    File,
    #[serde(rename = "action")]
    Action,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Text
    }
}
