/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRedditFlairs200Response {
    #[serde(rename = "flairs", skip_serializing_if = "Option::is_none")]
    pub flairs: Option<Vec<models::GetRedditFlairs200ResponseFlairsInner>>,
}

impl GetRedditFlairs200Response {
    pub fn new() -> GetRedditFlairs200Response {
        GetRedditFlairs200Response { flairs: None }
    }
}
