/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetInboxPostComments200ResponseMetaAdComments : (Facebook/Instagram only) Present when this post has no organic comments but is a boosted post — the engagement lives on the ad. Use the ad-comments endpoint instead.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetInboxPostComments200ResponseMetaAdComments {
    /// Internal Zernio ad ID
    #[serde(rename = "adId", skip_serializing_if = "Option::is_none")]
    pub ad_id: Option<String>,
    /// Path to fetch the ad's comments (GET /v1/ads/{adId}/comments)
    #[serde(rename = "adCommentsUrl", skip_serializing_if = "Option::is_none")]
    pub ad_comments_url: Option<String>,
}

impl GetInboxPostComments200ResponseMetaAdComments {
    /// (Facebook/Instagram only) Present when this post has no organic comments but is a boosted post — the engagement lives on the ad. Use the ad-comments endpoint instead.
    pub fn new() -> GetInboxPostComments200ResponseMetaAdComments {
        GetInboxPostComments200ResponseMetaAdComments {
            ad_id: None,
            ad_comments_url: None,
        }
    }
}
