/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWhatsAppGroups200ResponseSummary {
    #[serde(rename = "totalContacts", skip_serializing_if = "Option::is_none")]
    pub total_contacts: Option<i32>,
    #[serde(rename = "optedInContacts", skip_serializing_if = "Option::is_none")]
    pub opted_in_contacts: Option<i32>,
    #[serde(rename = "groupCount", skip_serializing_if = "Option::is_none")]
    pub group_count: Option<i32>,
}

impl GetWhatsAppGroups200ResponseSummary {
    pub fn new() -> GetWhatsAppGroups200ResponseSummary {
        GetWhatsAppGroups200ResponseSummary {
            total_contacts: None,
            opted_in_contacts: None,
            group_count: None,
        }
    }
}
