/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDiscordChannels200Response {
    #[serde(rename = "channels", skip_serializing_if = "Option::is_none")]
    pub channels: Option<Vec<models::GetDiscordChannels200ResponseChannelsInner>>,
}

impl GetDiscordChannels200Response {
    pub fn new() -> GetDiscordChannels200Response {
        GetDiscordChannels200Response { channels: None }
    }
}
