/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetTikTokCreatorInfo200ResponsePostingLimitsInteractionSettings : Per-interaction descriptors for the comment, duet and stitch toggles. Each key matches the tiktokSettings field of the same name on the create-post request. allow_duet and allow_stitch are null when mediaType is photo, because TikTok does not apply duet or stitch to photo posts.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTikTokCreatorInfo200ResponsePostingLimitsInteractionSettings {
    #[serde(rename = "allow_comment", skip_serializing_if = "Option::is_none")]
    pub allow_comment: Option<
        Box<models::GetTikTokCreatorInfo200ResponsePostingLimitsInteractionSettingsAllowComment>,
    >,
    #[serde(rename = "allow_duet", skip_serializing_if = "Option::is_none")]
    pub allow_duet: Option<
        Box<models::GetTikTokCreatorInfo200ResponsePostingLimitsInteractionSettingsAllowDuet>,
    >,
    #[serde(rename = "allow_stitch", skip_serializing_if = "Option::is_none")]
    pub allow_stitch: Option<
        Box<models::GetTikTokCreatorInfo200ResponsePostingLimitsInteractionSettingsAllowStitch>,
    >,
}

impl GetTikTokCreatorInfo200ResponsePostingLimitsInteractionSettings {
    /// Per-interaction descriptors for the comment, duet and stitch toggles. Each key matches the tiktokSettings field of the same name on the create-post request. allow_duet and allow_stitch are null when mediaType is photo, because TikTok does not apply duet or stitch to photo posts.
    pub fn new() -> GetTikTokCreatorInfo200ResponsePostingLimitsInteractionSettings {
        GetTikTokCreatorInfo200ResponsePostingLimitsInteractionSettings {
            allow_comment: None,
            allow_duet: None,
            allow_stitch: None,
        }
    }
}
