/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSlackSettings200ResponseAccount {
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub _id: Option<String>,
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
    #[serde(
        rename = "displayName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<Option<String>>,
    #[serde(
        rename = "channelId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub channel_id: Option<Option<String>>,
    #[serde(
        rename = "channelName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub channel_name: Option<Option<String>>,
    /// public or private
    #[serde(
        rename = "channelType",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub channel_type: Option<Option<String>>,
    #[serde(
        rename = "teamId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub team_id: Option<Option<String>>,
    #[serde(
        rename = "teamName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub team_name: Option<Option<String>>,
    #[serde(
        rename = "defaultUsername",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_username: Option<Option<String>>,
    #[serde(
        rename = "defaultIconUrl",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_icon_url: Option<Option<String>>,
}

impl GetSlackSettings200ResponseAccount {
    pub fn new() -> GetSlackSettings200ResponseAccount {
        GetSlackSettings200ResponseAccount {
            _id: None,
            platform: None,
            display_name: None,
            channel_id: None,
            channel_name: None,
            channel_type: None,
            team_id: None,
            team_name: None,
            default_username: None,
            default_icon_url: None,
        }
    }
}
