/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCampaignAnalytics202Response {
    #[serde(rename = "backfillPending")]
    pub backfill_pending: BackfillPending,
    #[serde(rename = "campaign", skip_serializing_if = "Option::is_none")]
    pub campaign: Option<Box<models::CampaignAnalyticsResponseCampaign>>,
    #[serde(rename = "analytics", skip_serializing_if = "Option::is_none")]
    pub analytics: Option<Box<models::CampaignAnalyticsResponseAnalytics>>,
}

impl GetCampaignAnalytics202Response {
    pub fn new(backfill_pending: BackfillPending) -> GetCampaignAnalytics202Response {
        GetCampaignAnalytics202Response {
            backfill_pending,
            campaign: None,
            analytics: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BackfillPending {
    #[serde(rename = "true")]
    True,
}

impl Default for BackfillPending {
    fn default() -> BackfillPending {
        Self::True
    }
}
