/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDailyMetrics200ResponseDailyDataInner {
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "postCount", skip_serializing_if = "Option::is_none")]
    pub post_count: Option<i32>,
    #[serde(rename = "platforms", skip_serializing_if = "Option::is_none")]
    pub platforms: Option<std::collections::HashMap<String, i32>>,
    #[serde(rename = "metrics", skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Box<models::GetDailyMetrics200ResponseDailyDataInnerMetrics>>,
}

impl GetDailyMetrics200ResponseDailyDataInner {
    pub fn new() -> GetDailyMetrics200ResponseDailyDataInner {
        GetDailyMetrics200ResponseDailyDataInner {
            date: None,
            post_count: None,
            platforms: None,
            metrics: None,
        }
    }
}
