/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetInboxConversationMessages200ResponseMessagesInnerDeliveryError : Populated when deliveryStatus === \"failed\".
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetInboxConversationMessages200ResponseMessagesInnerDeliveryError {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl GetInboxConversationMessages200ResponseMessagesInnerDeliveryError {
    /// Populated when deliveryStatus === \"failed\".
    pub fn new() -> GetInboxConversationMessages200ResponseMessagesInnerDeliveryError {
        GetInboxConversationMessages200ResponseMessagesInnerDeliveryError {
            code: None,
            title: None,
            message: None,
        }
    }
}
