/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.
 *
 * The version of the OpenAPI document: 1.220.2
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetTrackingTagStoreInstall200ResponseInstallAllOfPreflight : WordPress only.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTrackingTagStoreInstall200ResponseInstallAllOfPreflight {
    /// True when POST should be able to install.
    #[serde(rename = "ready", skip_serializing_if = "Option::is_none")]
    pub ready: Option<bool>,
    /// A TrackingTagInstallBlockedReason when an install would be blocked, else null.
    #[serde(
        rename = "reason",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reason: Option<Option<String>>,
    /// Active widget areas of the theme.
    #[serde(rename = "sidebars", skip_serializing_if = "Option::is_none")]
    pub sidebars: Option<Vec<models::UpdateFacebookPage200ResponseSelectedPage>>,
}

impl GetTrackingTagStoreInstall200ResponseInstallAllOfPreflight {
    /// WordPress only.
    pub fn new() -> GetTrackingTagStoreInstall200ResponseInstallAllOfPreflight {
        GetTrackingTagStoreInstall200ResponseInstallAllOfPreflight {
            ready: None,
            reason: None,
            sidebars: None,
        }
    }
}
