/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstagramAccountInsightsResponseMetricsValueBreakdownsInner {
    #[serde(rename = "dimension", skip_serializing_if = "Option::is_none")]
    pub dimension: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f64>,
}

impl InstagramAccountInsightsResponseMetricsValueBreakdownsInner {
    pub fn new() -> InstagramAccountInsightsResponseMetricsValueBreakdownsInner {
        InstagramAccountInsightsResponseMetricsValueBreakdownsInner {
            dimension: None,
            value: None,
        }
    }
}
