/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LikeInboxCommentRequest {
    /// The social account ID
    #[serde(rename = "accountId")]
    pub account_id: String,
    /// (Bluesky only) Content identifier for the comment
    #[serde(rename = "cid", skip_serializing_if = "Option::is_none")]
    pub cid: Option<String>,
}

impl LikeInboxCommentRequest {
    pub fn new(account_id: String) -> LikeInboxCommentRequest {
        LikeInboxCommentRequest {
            account_id,
            cid: None,
        }
    }
}
