/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkedInAdsPlatformDataFollowerHeadline {
    /// LinkedIn preset id, not reviewed. Example GROW_YOUR_BUSINESS_INSIGHTS.
    #[serde(rename = "preApproved", skip_serializing_if = "Option::is_none")]
    pub pre_approved: Option<String>,
    /// Free text, reviewed by LinkedIn.
    #[serde(rename = "custom", skip_serializing_if = "Option::is_none")]
    pub custom: Option<String>,
}

impl LinkedInAdsPlatformDataFollowerHeadline {
    pub fn new() -> LinkedInAdsPlatformDataFollowerHeadline {
        LinkedInAdsPlatformDataFollowerHeadline {
            pre_approved: None,
            custom: None,
        }
    }
}
