/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAdAccounts200ResponseAccountsInner {
    /// Platform ad account ID (e.g. act_123)
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// IANA timezone of the ad account (Meta only). Drives daily-budget reset and Insights day boundaries.
    #[serde(rename = "timezoneName", skip_serializing_if = "Option::is_none")]
    pub timezone_name: Option<String>,
    /// Signed UTC offset in hours, reflecting current DST (Meta only).
    #[serde(
        rename = "timezoneOffsetHoursUtc",
        skip_serializing_if = "Option::is_none"
    )]
    pub timezone_offset_hours_utc: Option<f64>,
}

impl ListAdAccounts200ResponseAccountsInner {
    pub fn new() -> ListAdAccounts200ResponseAccountsInner {
        ListAdAccounts200ResponseAccountsInner {
            id: None,
            name: None,
            currency: None,
            status: None,
            timezone_name: None,
            timezone_offset_hours_utc: None,
        }
    }
}
