/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.
 *
 * The version of the OpenAPI document: 1.92.0
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListAdSets200ResponseAdSetsInnerTargeting : The audience this ad set delivers to, as the platform reports it. LinkedIn only today; null for every other platform and for LinkedIn ad sets not yet re-synced.  `include` and `exclude` are the campaign's `targetingCriteria` verbatim, so they can be read, edited and sent back without reconstructing them from our normalized targeting spec. Exclusions were previously not readable at all.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAdSets200ResponseAdSetsInnerTargeting {
    /// LinkedIn `targetingCriteria.include`, verbatim (an `and` of `or` facet clauses).
    #[serde(rename = "include", skip_serializing_if = "Option::is_none")]
    pub include: Option<serde_json::Value>,
    /// LinkedIn `targetingCriteria.exclude`, verbatim. Absent when the campaign excludes nothing.
    #[serde(rename = "exclude", skip_serializing_if = "Option::is_none")]
    pub exclude: Option<serde_json::Value>,
    /// LinkedIn audience expansion: whether LinkedIn may also serve to members similar to the criteria.
    #[serde(
        rename = "audienceExpansionEnabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub audience_expansion_enabled: Option<bool>,
    /// Whether the campaign may deliver on the LinkedIn Audience Network, off LinkedIn itself.
    #[serde(
        rename = "offsiteDeliveryEnabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub offsite_delivery_enabled: Option<bool>,
}

impl ListAdSets200ResponseAdSetsInnerTargeting {
    /// The audience this ad set delivers to, as the platform reports it. LinkedIn only today; null for every other platform and for LinkedIn ad sets not yet re-synced.  `include` and `exclude` are the campaign's `targetingCriteria` verbatim, so they can be read, edited and sent back without reconstructing them from our normalized targeting spec. Exclusions were previously not readable at all.
    pub fn new() -> ListAdSets200ResponseAdSetsInnerTargeting {
        ListAdSets200ResponseAdSetsInnerTargeting {
            include: None,
            exclude: None,
            audience_expansion_enabled: None,
            offsite_delivery_enabled: None,
        }
    }
}
