/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSmsSenderIds200Response {
    #[serde(rename = "senderIds", skip_serializing_if = "Option::is_none")]
    pub sender_ids: Option<Vec<models::ListSmsSenderIds200ResponseSenderIdsInner>>,
    #[serde(rename = "budget", skip_serializing_if = "Option::is_none")]
    pub budget: Option<Box<models::ListSmsSenderIds200ResponseBudget>>,
}

impl ListSmsSenderIds200Response {
    pub fn new() -> ListSmsSenderIds200Response {
        ListSmsSenderIds200Response {
            sender_ids: None,
            budget: None,
        }
    }
}
