/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.
 *
 * The version of the OpenAPI document: 1.239.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAdGroupAssets200ResponseImagesInner {
    #[serde(rename = "assetResourceName", skip_serializing_if = "Option::is_none")]
    pub asset_resource_name: Option<String>,
    #[serde(
        rename = "adGroupAssetResourceName",
        skip_serializing_if = "Option::is_none"
    )]
    pub ad_group_asset_resource_name: Option<String>,
    /// Google-hosted copy of the image.
    #[serde(rename = "imageUrl", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
}

impl ListAdGroupAssets200ResponseImagesInner {
    pub fn new() -> ListAdGroupAssets200ResponseImagesInner {
        ListAdGroupAssets200ResponseImagesInner {
            asset_resource_name: None,
            ad_group_asset_resource_name: None,
            image_url: None,
            width: None,
            height: None,
        }
    }
}
