/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAdCatalogs200ResponseCatalogsInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Catalog vertical (e.g. commerce, vehicles, hotels)
    #[serde(
        rename = "vertical",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub vertical: Option<Option<String>>,
    #[serde(rename = "productCount", skip_serializing_if = "Option::is_none")]
    pub product_count: Option<i32>,
}

impl ListAdCatalogs200ResponseCatalogsInner {
    pub fn new() -> ListAdCatalogs200ResponseCatalogsInner {
        ListAdCatalogs200ResponseCatalogsInner {
            id: None,
            name: None,
            vertical: None,
            product_count: None,
        }
    }
}
