/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListInboxReviews200ResponseSummary {
    #[serde(rename = "totalReviews", skip_serializing_if = "Option::is_none")]
    pub total_reviews: Option<i32>,
    #[serde(
        rename = "averageRating",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub average_rating: Option<Option<f64>>,
}

impl ListInboxReviews200ResponseSummary {
    pub fn new() -> ListInboxReviews200ResponseSummary {
        ListInboxReviews200ResponseSummary {
            total_reviews: None,
            average_rating: None,
        }
    }
}
