/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListCommentAutomationLogs200ResponseMissesSamplesInner {
    #[serde(rename = "commentText", skip_serializing_if = "Option::is_none")]
    pub comment_text: Option<String>,
    #[serde(rename = "commenterName", skip_serializing_if = "Option::is_none")]
    pub commenter_name: Option<String>,
    /// Set when an exclusion keyword vetoed an otherwise matching comment
    #[serde(rename = "excludedBy", skip_serializing_if = "Option::is_none")]
    pub excluded_by: Option<String>,
    #[serde(rename = "at", skip_serializing_if = "Option::is_none")]
    pub at: Option<String>,
}

impl ListCommentAutomationLogs200ResponseMissesSamplesInner {
    pub fn new() -> ListCommentAutomationLogs200ResponseMissesSamplesInner {
        ListCommentAutomationLogs200ResponseMissesSamplesInner {
            comment_text: None,
            commenter_name: None,
            excluded_by: None,
            at: None,
        }
    }
}
