/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.
 *
 * The version of the OpenAPI document: 1.99.0
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListAdAccounts200ResponseAccountsInnerFundingSourceDetails : Meta only. Meta's `funding_source_details` object, forwarded unchanged. ABSENT under exactly the same conditions as `fundingSource`, never sent as null or as an empty object. Read `billingStatus` for what the absence means.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAdAccounts200ResponseAccountsInnerFundingSourceDetails {
    /// Meta's ID for the funding instrument. Matches `fundingSource`.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Meta's own human-readable label for the funding instrument, e.g. 'Available Balance (EUR)' or a masked card. Meta composes this string; do not parse it.
    #[serde(rename = "displayString", skip_serializing_if = "Option::is_none")]
    pub display_string: Option<String>,
    /// Meta's raw numeric funding-source type, forwarded unchanged. Meta publishes no mapping from these numbers to payment-method kinds, so none is documented here and none should be inferred.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<i32>,
}

impl ListAdAccounts200ResponseAccountsInnerFundingSourceDetails {
    /// Meta only. Meta's `funding_source_details` object, forwarded unchanged. ABSENT under exactly the same conditions as `fundingSource`, never sent as null or as an empty object. Read `billingStatus` for what the absence means.
    pub fn new() -> ListAdAccounts200ResponseAccountsInnerFundingSourceDetails {
        ListAdAccounts200ResponseAccountsInnerFundingSourceDetails {
            id: None,
            display_string: None,
            r#type: None,
        }
    }
}
