/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListWorkflowExecutions200Response {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "executions", skip_serializing_if = "Option::is_none")]
    pub executions: Option<Vec<models::ListWorkflowExecutions200ResponseExecutionsInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::ListContacts200ResponsePagination>>,
}

impl ListWorkflowExecutions200Response {
    pub fn new() -> ListWorkflowExecutions200Response {
        ListWorkflowExecutions200Response {
            success: None,
            executions: None,
            pagination: None,
        }
    }
}
