/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Money {
    /// ISO 4217 currency code (e.g. USD, EUR)
    #[serde(rename = "currencyCode")]
    pub currency_code: String,
    /// Whole units of the amount
    #[serde(rename = "units")]
    pub units: String,
    /// Nano units (10^-9) of the amount
    #[serde(rename = "nanos", skip_serializing_if = "Option::is_none")]
    pub nanos: Option<i32>,
}

impl Money {
    pub fn new(currency_code: String, units: String) -> Money {
        Money {
            currency_code,
            units,
            nanos: None,
        }
    }
}
