/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreflightSmsRegistrationRequest {
    #[serde(rename = "registrationType")]
    pub registration_type: RegistrationType,
    #[serde(rename = "phoneNumbers", skip_serializing_if = "Option::is_none")]
    pub phone_numbers: Option<Vec<String>>,
    /// Same shape as the registration `brand`.
    #[serde(rename = "brand")]
    pub brand: serde_json::Value,
    /// Same shape as the registration `campaign`.
    #[serde(rename = "campaign")]
    pub campaign: serde_json::Value,
    #[serde(rename = "messagingBrandName", skip_serializing_if = "Option::is_none")]
    pub messaging_brand_name: Option<String>,
}

impl PreflightSmsRegistrationRequest {
    pub fn new(
        registration_type: RegistrationType,
        brand: serde_json::Value,
        campaign: serde_json::Value,
    ) -> PreflightSmsRegistrationRequest {
        PreflightSmsRegistrationRequest {
            registration_type,
            phone_numbers: None,
            brand,
            campaign,
            messaging_brand_name: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RegistrationType {
    #[serde(rename = "standard_10dlc")]
    Standard10dlc,
    #[serde(rename = "sole_prop_10dlc")]
    SoleProp10dlc,
}

impl Default for RegistrationType {
    fn default() -> RegistrationType {
        Self::Standard10dlc
    }
}
