/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PurchasePhoneNumber202Response {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(rename = "kycUrl", skip_serializing_if = "Option::is_none")]
    pub kyc_url: Option<String>,
}

impl PurchasePhoneNumber202Response {
    pub fn new() -> PurchasePhoneNumber202Response {
        PurchasePhoneNumber202Response {
            status: None,
            country: None,
            kyc_url: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "kyc_required")]
    KycRequired,
}

impl Default for Status {
    fn default() -> Status {
        Self::KycRequired
    }
}
