/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PurchaseWhatsAppPhoneNumber200ResponseOneOf1 : A number was already purchased under the supplied purchaseIntentId; no new number was provisioned.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PurchaseWhatsAppPhoneNumber200ResponseOneOf1 {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "numberId", skip_serializing_if = "Option::is_none")]
    pub number_id: Option<String>,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
}

impl PurchaseWhatsAppPhoneNumber200ResponseOneOf1 {
    /// A number was already purchased under the supplied purchaseIntentId; no new number was provisioned.
    pub fn new() -> PurchaseWhatsAppPhoneNumber200ResponseOneOf1 {
        PurchaseWhatsAppPhoneNumber200ResponseOneOf1 {
            status: None,
            number_id: None,
            phone_number: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "already_purchased")]
    AlreadyPurchased,
}

impl Default for Status {
    fn default() -> Status {
        Self::AlreadyPurchased
    }
}
