/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemediateWhatsAppNumber200Response {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<Box<models::RemediateWhatsAppNumber200ResponsePhoneNumber>>,
}

impl RemediateWhatsAppNumber200Response {
    pub fn new() -> RemediateWhatsAppNumber200Response {
        RemediateWhatsAppNumber200Response {
            status: None,
            phone_number: None,
        }
    }
}
