/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleWhatsAppBroadcast200Response {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "broadcast", skip_serializing_if = "Option::is_none")]
    pub broadcast: Option<Box<models::ScheduleWhatsAppBroadcast200ResponseBroadcast>>,
}

impl ScheduleWhatsAppBroadcast200Response {
    pub fn new() -> ScheduleWhatsAppBroadcast200Response {
        ScheduleWhatsAppBroadcast200Response {
            success: None,
            broadcast: None,
        }
    }
}
