/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchInboxConversations200ResponseMeta {
    #[serde(rename = "accountsQueried", skip_serializing_if = "Option::is_none")]
    pub accounts_queried: Option<i32>,
    #[serde(rename = "accountsFailed", skip_serializing_if = "Option::is_none")]
    pub accounts_failed: Option<i32>,
    #[serde(rename = "failedAccounts", skip_serializing_if = "Option::is_none")]
    pub failed_accounts:
        Option<Vec<models::SearchInboxConversations200ResponseMetaFailedAccountsInner>>,
    #[serde(rename = "lastUpdated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
    /// Connected messaging accounts that cannot be searched (live-fetched platforms)
    #[serde(rename = "accountsSkipped", skip_serializing_if = "Option::is_none")]
    pub accounts_skipped:
        Option<Vec<models::SearchInboxConversations200ResponseMetaAccountsSkippedInner>>,
}

impl SearchInboxConversations200ResponseMeta {
    pub fn new() -> SearchInboxConversations200ResponseMeta {
        SearchInboxConversations200ResponseMeta {
            accounts_queried: None,
            accounts_failed: None,
            failed_accounts: None,
            last_updated: None,
            accounts_skipped: None,
        }
    }
}
