/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchAvailableWhatsAppNumbers200Response {
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(rename = "numberType", skip_serializing_if = "Option::is_none")]
    pub number_type: Option<String>,
    #[serde(rename = "numbers", skip_serializing_if = "Option::is_none")]
    pub numbers: Option<Vec<models::SearchAvailableWhatsAppNumbers200ResponseNumbersInner>>,
}

impl SearchAvailableWhatsAppNumbers200Response {
    pub fn new() -> SearchAvailableWhatsAppNumbers200Response {
        SearchAvailableWhatsAppNumbers200Response {
            country: None,
            number_type: None,
            numbers: None,
        }
    }
}
