/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchAdTargetingLocations200Response {
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<models::SearchAdTargetingLocations200ResponseResultsInner>>,
}

impl SearchAdTargetingLocations200Response {
    pub fn new() -> SearchAdTargetingLocations200Response {
        SearchAdTargetingLocations200Response { results: None }
    }
}
