/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelectLinkedInOrganization200Response {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// The redirect URL with connection params appended (only if redirect_url was provided in request)
    #[serde(rename = "redirect_url", skip_serializing_if = "Option::is_none")]
    pub redirect_url: Option<String>,
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<Box<models::SelectLinkedInOrganization200ResponseAccount>>,
    #[serde(rename = "bulkRefresh", skip_serializing_if = "Option::is_none")]
    pub bulk_refresh: Option<Box<models::SelectLinkedInOrganization200ResponseBulkRefresh>>,
}

impl SelectLinkedInOrganization200Response {
    pub fn new() -> SelectLinkedInOrganization200Response {
        SelectLinkedInOrganization200Response {
            message: None,
            redirect_url: None,
            account: None,
            bulk_refresh: None,
        }
    }
}
