/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetInstagramIceBreakersRequestIceBreakersInner {
    #[serde(rename = "question")]
    pub question: String,
    #[serde(rename = "payload")]
    pub payload: String,
}

impl SetInstagramIceBreakersRequestIceBreakersInner {
    pub fn new(
        question: String,
        payload: String,
    ) -> SetInstagramIceBreakersRequestIceBreakersInner {
        SetInstagramIceBreakersRequestIceBreakersInner { question, payload }
    }
}
