/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StartWhatsAppCallerIdVerification200Response {
    #[serde(rename = "verified", skip_serializing_if = "Option::is_none")]
    pub verified: Option<bool>,
    #[serde(rename = "codeSent", skip_serializing_if = "Option::is_none")]
    pub code_sent: Option<bool>,
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<Method>,
}

impl StartWhatsAppCallerIdVerification200Response {
    pub fn new() -> StartWhatsAppCallerIdVerification200Response {
        StartWhatsAppCallerIdVerification200Response {
            verified: None,
            code_sent: None,
            method: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Method {
    #[serde(rename = "sms")]
    Sms,
    #[serde(rename = "call")]
    Call,
}

impl Default for Method {
    fn default() -> Method {
        Self::Sms
    }
}
