/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StartSmsRegistration200Response {
    #[serde(rename = "registrationId", skip_serializing_if = "Option::is_none")]
    pub registration_id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// True for sole-prop 10DLC: an OTP was texted to the brand's mobile; submit it via /verify-otp.
    #[serde(rename = "awaitingOtp", skip_serializing_if = "Option::is_none")]
    pub awaiting_otp: Option<bool>,
}

impl StartSmsRegistration200Response {
    pub fn new() -> StartSmsRegistration200Response {
        StartSmsRegistration200Response {
            registration_id: None,
            status: None,
            awaiting_otp: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "pending")]
    Pending,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pending
    }
}
