/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubmitPhoneNumberKyc200ResponsePhoneNumber : The first/primary number, kept at the top level for backward compatibility. See `numbers` for the full set when `quantity` > 1.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitPhoneNumberKyc200ResponsePhoneNumber {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
}

impl SubmitPhoneNumberKyc200ResponsePhoneNumber {
    /// The first/primary number, kept at the top level for backward compatibility. See `numbers` for the full set when `quantity` > 1.
    pub fn new() -> SubmitPhoneNumberKyc200ResponsePhoneNumber {
        SubmitPhoneNumberKyc200ResponsePhoneNumber {
            id: None,
            status: None,
            country: None,
        }
    }
}
