/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateConversionDestinationRequestValue : Used when `valueType=FIXED`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateConversionDestinationRequestValue {
    /// ISO 4217.
    #[serde(rename = "currencyCode", skip_serializing_if = "Option::is_none")]
    pub currency_code: Option<String>,
    /// Decimal string (e.g. \"49.99\").
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
}

impl UpdateConversionDestinationRequestValue {
    /// Used when `valueType=FIXED`.
    pub fn new() -> UpdateConversionDestinationRequestValue {
        UpdateConversionDestinationRequestValue {
            currency_code: None,
            amount: None,
        }
    }
}
