/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAdTrackingTagsRequest {
    /// Meta only. Click-URL params appended to a freshly-rebuilt creative.
    #[serde(rename = "urlTags", skip_serializing_if = "Option::is_none")]
    pub url_tags: Option<Vec<models::UpdateAdTrackingTagsRequestUrlTagsInner>>,
    #[serde(rename = "creative", skip_serializing_if = "Option::is_none")]
    pub creative: Option<Box<models::UpdateAdTrackingTagsRequestCreative>>,
    /// Google only. Full tracking template (must contain {lpurl}).
    #[serde(
        rename = "trackingUrlTemplate",
        skip_serializing_if = "Option::is_none"
    )]
    pub tracking_url_template: Option<String>,
    /// Google only. Parse-only key=value params.
    #[serde(rename = "finalUrlSuffix", skip_serializing_if = "Option::is_none")]
    pub final_url_suffix: Option<String>,
    /// LinkedIn only. key -> dynamic value enum (CAMPAIGN_ID, CAMPAIGN_NAME, CREATIVE_ID, ...).
    #[serde(
        rename = "dynamicValueParameters",
        skip_serializing_if = "Option::is_none"
    )]
    pub dynamic_value_parameters: Option<std::collections::HashMap<String, String>>,
    /// LinkedIn only. key -> static value.
    #[serde(
        rename = "customValueParameters",
        skip_serializing_if = "Option::is_none"
    )]
    pub custom_value_parameters: Option<std::collections::HashMap<String, String>>,
}

impl UpdateAdTrackingTagsRequest {
    pub fn new() -> UpdateAdTrackingTagsRequest {
        UpdateAdTrackingTagsRequest {
            url_tags: None,
            creative: None,
            tracking_url_template: None,
            final_url_suffix: None,
            dynamic_value_parameters: None,
            custom_value_parameters: None,
        }
    }
}
