/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWhatsAppTemplateRequest {
    /// WhatsApp social account ID
    #[serde(rename = "accountId")]
    pub account_id: String,
    /// Updated template components
    #[serde(rename = "components")]
    pub components: Vec<serde_json::Value>,
}

impl UpdateWhatsAppTemplateRequest {
    pub fn new(
        account_id: String,
        components: Vec<serde_json::Value>,
    ) -> UpdateWhatsAppTemplateRequest {
        UpdateWhatsAppTemplateRequest {
            account_id,
            components,
        }
    }
}
