/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.
 *
 * The version of the OpenAPI document: 1.226.0
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAdAccountRequest {
    /// Account ID (metaads, or a facebook/instagram posting account)
    #[serde(rename = "accountId")]
    pub account_id: String,
    /// Meta ad account ID (act_...)
    #[serde(rename = "adAccountId")]
    pub ad_account_id: String,
    /// New ad account name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Account spend cap in whole currency units; null removes it.
    #[serde(
        rename = "spendCap",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub spend_cap: Option<Option<f64>>,
    /// Restart the amount counted against the cap from zero. Cannot be combined with spendCap null.
    #[serde(rename = "resetAmountSpent", skip_serializing_if = "Option::is_none")]
    pub reset_amount_spent: Option<bool>,
    /// Legal entity benefiting from ads on this ad account
    #[serde(
        rename = "defaultDsaBeneficiary",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_dsa_beneficiary: Option<String>,
    /// Legal entity paying for ads on this ad account. Defaults to defaultDsaBeneficiary when omitted. Requires defaultDsaBeneficiary.
    #[serde(rename = "defaultDsaPayor", skip_serializing_if = "Option::is_none")]
    pub default_dsa_payor: Option<String>,
}

impl UpdateAdAccountRequest {
    pub fn new(account_id: String, ad_account_id: String) -> UpdateAdAccountRequest {
        UpdateAdAccountRequest {
            account_id,
            ad_account_id,
            name: None,
            spend_cap: None,
            reset_amount_spent: None,
            default_dsa_beneficiary: None,
            default_dsa_payor: None,
        }
    }
}
