/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAdRequestTargetingKeywordsInnerOneOf {
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "matchType", skip_serializing_if = "Option::is_none")]
    pub match_type: Option<MatchType>,
}

impl UpdateAdRequestTargetingKeywordsInnerOneOf {
    pub fn new(text: String) -> UpdateAdRequestTargetingKeywordsInnerOneOf {
        UpdateAdRequestTargetingKeywordsInnerOneOf {
            text,
            match_type: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MatchType {
    #[serde(rename = "exact")]
    Exact,
    #[serde(rename = "phrase")]
    Phrase,
    #[serde(rename = "broad")]
    Broad,
}

impl Default for MatchType {
    fn default() -> MatchType {
        Self::Exact
    }
}
