/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateGoogleBusinessAttributesRequest {
    #[serde(rename = "attributes")]
    pub attributes: Vec<models::UpdateGoogleBusinessAttributesRequestAttributesInner>,
    /// Comma-separated attribute names to update (e.g. 'has_delivery,has_takeout')
    #[serde(rename = "attributeMask")]
    pub attribute_mask: String,
}

impl UpdateGoogleBusinessAttributesRequest {
    pub fn new(
        attributes: Vec<models::UpdateGoogleBusinessAttributesRequestAttributesInner>,
        attribute_mask: String,
    ) -> UpdateGoogleBusinessAttributesRequest {
        UpdateGoogleBusinessAttributesRequest {
            attributes,
            attribute_mask,
        }
    }
}
