/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateAdRequestTargetingKeywordsInner {
    String(String),
    UpdateAdRequestTargetingKeywordsInnerOneOf(
        Box<models::UpdateAdRequestTargetingKeywordsInnerOneOf>,
    ),
}

impl Default for UpdateAdRequestTargetingKeywordsInner {
    fn default() -> Self {
        Self::String(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MatchType {
    #[serde(rename = "exact")]
    Exact,
    #[serde(rename = "phrase")]
    Phrase,
    #[serde(rename = "broad")]
    Broad,
}

impl Default for MatchType {
    fn default() -> MatchType {
        Self::Exact
    }
}
