/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidatePostLengthRequest {
    /// The post text to check
    #[serde(rename = "text")]
    pub text: String,
}

impl ValidatePostLengthRequest {
    pub fn new(text: String) -> ValidatePostLengthRequest {
        ValidatePostLengthRequest { text }
    }
}
