/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookPayloadAccountDisconnected : Webhook payload for account disconnected events
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookPayloadAccountDisconnected {
    /// Stable webhook event ID
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "event")]
    pub event: Event,
    #[serde(rename = "account")]
    pub account: Box<models::WebhookPayloadAccountDisconnectedAccount>,
    /// UTC time at which Zernio generated this event (set once when the event payload is built, before delivery is queued). Retries and redeliveries keep the original value, so it reflects the event, not the delivery attempt.
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl WebhookPayloadAccountDisconnected {
    /// Webhook payload for account disconnected events
    pub fn new(
        id: String,
        event: Event,
        account: models::WebhookPayloadAccountDisconnectedAccount,
        timestamp: String,
    ) -> WebhookPayloadAccountDisconnected {
        WebhookPayloadAccountDisconnected {
            id,
            event,
            account: Box::new(account),
            timestamp,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "account.disconnected")]
    AccountDisconnected,
}

impl Default for Event {
    fn default() -> Event {
        Self::AccountDisconnected
    }
}
