/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookPayloadMessageDeliveryStatus : Shared payload for `message.delivered`, `message.read`, and `message.failed` events. Fires when the platform reports a new delivery state for an outgoing message.  Platform support:   * `message.delivered` — WhatsApp, Facebook Messenger.   * `message.read`      — WhatsApp, Facebook Messenger, Instagram.   * `message.failed`    — WhatsApp only (other platforms don't expose     per-message failure via webhook).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookPayloadMessageDeliveryStatus {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "event")]
    pub event: Event,
    #[serde(rename = "message")]
    pub message: Box<models::WebhookPayloadMessageMessage>,
    /// When the platform reported this status.
    #[serde(rename = "statusAt")]
    pub status_at: String,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::WebhookPayloadMessageDeliveryStatusError>>,
    #[serde(rename = "conversation")]
    pub conversation: Box<models::WebhookPayloadMessageConversation>,
    #[serde(rename = "account")]
    pub account: Box<models::WebhookPayloadMessageAccount>,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl WebhookPayloadMessageDeliveryStatus {
    /// Shared payload for `message.delivered`, `message.read`, and `message.failed` events. Fires when the platform reports a new delivery state for an outgoing message.  Platform support:   * `message.delivered` — WhatsApp, Facebook Messenger.   * `message.read`      — WhatsApp, Facebook Messenger, Instagram.   * `message.failed`    — WhatsApp only (other platforms don't expose     per-message failure via webhook).
    pub fn new(
        id: String,
        event: Event,
        message: models::WebhookPayloadMessageMessage,
        status_at: String,
        conversation: models::WebhookPayloadMessageConversation,
        account: models::WebhookPayloadMessageAccount,
        timestamp: String,
    ) -> WebhookPayloadMessageDeliveryStatus {
        WebhookPayloadMessageDeliveryStatus {
            id,
            event,
            message: Box::new(message),
            status_at,
            error: None,
            conversation: Box::new(conversation),
            account: Box::new(account),
            timestamp,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "message.delivered")]
    MessageDelivered,
    #[serde(rename = "message.read")]
    MessageRead,
    #[serde(rename = "message.failed")]
    MessageFailed,
}

impl Default for Event {
    fn default() -> Event {
        Self::MessageDelivered
    }
}
