/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WhatsAppCarouselComponent {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// 2-10 cards. Meta requires all cards to share the same component structure; a mismatch surfaces as a rejected_reason. MARKETING category only.
    #[serde(rename = "cards")]
    pub cards: Vec<models::WhatsAppCarouselComponentCardsInner>,
}

impl WhatsAppCarouselComponent {
    pub fn new(
        r#type: Type,
        cards: Vec<models::WhatsAppCarouselComponentCardsInner>,
    ) -> WhatsAppCarouselComponent {
        WhatsAppCarouselComponent { r#type, cards }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "carousel")]
    Carousel,
}

impl Default for Type {
    fn default() -> Type {
        Self::Carousel
    }
}
