/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct YouTubeDailyViewsResponseDailyViewsInner {
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "views", skip_serializing_if = "Option::is_none")]
    pub views: Option<i32>,
    #[serde(
        rename = "estimatedMinutesWatched",
        skip_serializing_if = "Option::is_none"
    )]
    pub estimated_minutes_watched: Option<f64>,
    /// Average view duration in seconds
    #[serde(
        rename = "averageViewDuration",
        skip_serializing_if = "Option::is_none"
    )]
    pub average_view_duration: Option<f64>,
    #[serde(rename = "subscribersGained", skip_serializing_if = "Option::is_none")]
    pub subscribers_gained: Option<i32>,
    #[serde(rename = "subscribersLost", skip_serializing_if = "Option::is_none")]
    pub subscribers_lost: Option<i32>,
    #[serde(rename = "likes", skip_serializing_if = "Option::is_none")]
    pub likes: Option<i32>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<i32>,
    #[serde(rename = "shares", skip_serializing_if = "Option::is_none")]
    pub shares: Option<i32>,
}

impl YouTubeDailyViewsResponseDailyViewsInner {
    pub fn new() -> YouTubeDailyViewsResponseDailyViewsInner {
        YouTubeDailyViewsResponseDailyViewsInner {
            date: None,
            views: None,
            estimated_minutes_watched: None,
            average_view_duration: None,
            subscribers_gained: None,
            subscribers_lost: None,
            likes: None,
            comments: None,
            shares: None,
        }
    }
}
